# Generated by Django 2.2.5 on 2019-09-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('artista', models.CharField(max_length=255, verbose_name='Idade')),
                ('genero', models.CharField(max_length=255, verbose_name='Genero')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
            ],
        ),
    ]
