# Generated by Django 2.2.5 on 2019-09-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_auto_20190906_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='link',
        ),
        migrations.AddField(
            model_name='musica',
            name='tempo',
            field=models.CharField(default=1, max_length=255, verbose_name='tempo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musica', to='artista.Artista'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='genero',
            field=models.CharField(max_length=255, verbose_name='tempo'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='nome'),
        ),
    ]
